name: CI/CD pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  workflow_dispatch:
    inputs:
      run_static_analysis_and_tests:
        description: "Indiquer si vous souhaitez lancer les analyses statiques et les tests (true/false)"
        required: false
        default: "true"
  schedule:
    - cron: "0 8 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build

      - name: Run static analysis and unit tests
        if: ${{ github.event_name == 'pull_request' || github.event.inputs.run_static_analysis_and_tests == 'true'}}
        run: |
          pnpm lint
          pnpm type-check

          pnpm test

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'push' }}
        with:
          name: dist
          path: dist
          retention-days: ${{ github.ref == 'refs/heads/main' && 7 || 1 }}

  deploy-qa:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          run: |
            ls -la dist
          path: dist

      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Install Azure Static Web Apps CLI
        run: |
          pnpm install -g @azure/static-web-apps-cli
      - name: Deploy to QA
        run: |
          swa deploy --source ./dist --app-name stapp-vue2048-qa --environment qa

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
