name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build

      - name: Run static analysis and unit tests
        if: ${{ github.event_name == 'pull_request' }}
        run: pnpm lint
          pnpm type-check

          pnpm test

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'push' }}
        with:
          name: app-package
          path: dist

  deploy-qa:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: QA deployment
        run: pnpm install -g @azure/static-web-apps-cli
          pnpm dlx @azure/static-web-apps-cli deploy ./dist --app-name stapp-vue2048-qa --env=qa

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
